sculpin_content_types:
    activities:
        layout: activity
        type: path
        singular_name: activity
        path: _activities
        permalink: activity/:basename.html
    pages:
        layout: default
        type: path
        singular_name: page
        path: _pages
        permalink: curriculum/:basename.html
        taxonomies:
            - tags
            - section
    resources:
        layout: default 
        type: path
        singular_name: resource
        path: _resources
        permalink: resource/:basename.html
    posts:
        permalink: blog/:year/:month/:day/:filename/
