sculpin_content_types:
    activities:
        singular_name: activity
        type: path
        path: _activities
        permalink: activity/:basename
        layout: activity
    pages:
        singular_name: page
        permalink: :filename/
        type: path
        path: _pages
        layout: default
        taxonomies:
            - tags
    posts:
        permalink: blog/:year/:month/:day/:filename/
